let nouns = [
  "cat",
  "keyboard",
  "mouse",
  "onion",
  "turtle",
  "cell phone",
  "backgammon game",
  "cassette tape",
  "movie",
  "pencil",
  "shirt",
  "brush",
  "tv",
  "car",
  "van",
  "goat",
  "zebra",
  "dog",
  "elephant",
  "seagull",
  "bat",
  "crab",
  "snail",
  "racoon",
  "bear",
  "teddy bear",
  "jeans",
  "t-shirt",
  "jeans",
  "dress",
  "skirt",
  "flower",
  "guitar",
  "sunhat",
  "fedora",
  "baseball hat",
  "sunglasses",
  "ripped jeans",
  "acoustic guitar",
  "watermellon",
  "dress shirt",
  "winter jacket",
  "cheeseburger",
  "cow",
  "pig",
  "picture frame",
  "wall art",
  "paint brush",
  "can of paint",
  "water",
];
let adjs = [
  "smelly",
  "sticky",
  "random",
  "gross",
  "putrid",
  "green",
  "hard",
  "soft",
  "bouncy",
  "lightweight",
  "beautiful",
  "nice",
];
let exclamations = [
  "wicked",
  "awesome",
  "totally rad",
  "so coooool",
  "terrific",
  "crazy awesome",
  "neato burrito",
  "sorta neat",
  "just ok",
  "not that great",
  "pretty awfull",
];

let firstNames = [
  "Aaliyah",
  "Aisha",
  "Ali",
  "Amir",
  "Amina",
  "Anas",
  "Asad",
  "Aya",
  "Ayah",
  "Aziz",
  "Bilal",
  "Danya",
  "Dawood",
  "Eman",
  "Faizan",
  "Fatima",
  "Faris",
  "Habib",
  "Hafsa",
  "Hassan",
  "Hiba",
  "Hussain",
  "Ibrahim",
  "Iman",
  "Inaya",
  "Iqra",
  "Jamal",
  "Jibril",
  "Kareem",
  "Khadija",
  "Khalid",
  "Layla",
  "Leena",
  "Lina",
  "Malik",
  "Mariah",
  "Marisha",
  "Marshaa",
  "Mariam",
  "Maryam",
  "Mohamed",
  "Muhammad",
  "Musa",
  "Nadia",
  "Naeem",
  "Nawal",
  "Noor",
  "Omar",
  "Qasim",
  "Rania",
  "Reem",
  "Riyad",
  "Safa",
  "Salma",
  "Sami",
  "Sara",
  "Selim",
  "Sumaya",
  "Tariq",
  "Yasir",
  "Yousuf",
  "Yasmin",
  "Zain",
  "Zara",
  "Zayd",
  "Zaynab",
  "Zubair",
];

let lastNames = [
  "Ahmad",
  "Ali",
  "Ansari",
  "Ashraf",
  "Bhat",
  "Butt",
  "Dar",
  "Farooqi",
  "Gilani",
  "Haider",
  "Hussain",
  "Khan",
  "Lone",
  "Malik",
  "Mir",
  "Naqvi",
  "Qadri",
  "Qureshi",
  "Raza",
  "Rehman",
  "Shah",
  "Shaikh",
  "Shamsi",
  "Siddiqui",
  "Sofi",
  "Syed",
  "Wani",
  "Yousuf",
  "Zargar",
  "Zehra",
  "Zubair",
  "Shafi",
  "Darzi",
  "Rather",
  "Reshi",
  "Ganai",
  "Bakshi",
  "Chowdhury",
  "Sheikh",
  "Pandit",
  "Mirza",
  "Masoodi",
  "Teli",
  "Chishti",
  "Geelani",
  "Rishi",
  "Tabasum",
  "Hamdani",
  "Makhdoomi",
];

let questions = [
  `Yo, why is my ${noun()} acting so ${adj()} these days? Any tips?`,
  `If you had a ${adj()} ${noun()}, what would you name it?`,
  `Which ${noun()} would you say is like, totally underrated?`,
  `What's a ${exc()} way to use a ${noun()}? Asking for a friend...`,
  `If my ${noun()} could talk, what do you think it'd say?`,
  `What's the best place to snag a ${exc()} ${noun()} around here?`,
  `Big Q: Who’s the top plug for ${adj()} ${noun()}s these days?`,
  `Help! My ${noun()} went missing... any leads?`,
  `What vibe would a ${adj()} ${noun()} give? Yay or nah?`,
  `If you had to dress as a ${noun()} for a day, which one would it be?`,
  `Is it just me, or is a ${adj()} ${noun()} totally overrated?`,
  `What's a ${exc()} secret talent of a ${noun()}? Spill!`,
  `If a ${noun()} could pick a theme song, what would it be?`,
  `Best way to level up my ${adj()} ${noun()} game?`,
  `I need some serious style inspo... what color ${noun()} should I rock?`,
  `Biggest flex you've seen involving a ${adj()} ${noun()}?`,
  `Real talk: What ${noun()} would you gift your worst enemy?`,
  `What's your ${exc()} tip for handling a ${adj()} ${noun()}?`,
  `So like, if you had to marry a ${noun()}, which one would it be?`,
  `Tell me the most ${exc()} use for a ${adj()} ${noun()}. Ready... go!`,
  `Rate my ${noun()} out of 10... be honest!`,
  `Would you rather have a ${adj()} ${noun()} or a super ${adj()} ${noun()}? Why?`,
  `What’s the wildest thing you’ve seen a ${noun()} do?`,
  `Would a ${adj()} ${noun()} make a good pet? Convince me!`,
  `What's a ${exc()} rumor you've heard about ${noun()}s?`,
  `Can a ${noun()} have feelings? Let's debate...`,
  `What’s the first thought you have when you see a ${adj()} ${noun()}?`,
  `What kind of vibes does a ${noun()} with ${adj()} features give off?`,
  `Pick a ${noun()} to go viral... which one?`,
  `Best caption for a pic with a ${adj()} ${noun()}?`,
  `If a ${noun()} was a celebrity, who would it be?`,
  `What’s the coolest thing about a ${adj()} ${noun()}?`,
  `Ever seen a ${noun()} used in a ${exc()} way? Do tell!`,
  `What's one thing people don’t know about ${noun()}s?`,
  `If a ${noun()} was your BFF, what would you call it?`,
  `If you could only have one ${adj()} ${noun()} for the rest of your life, would you?`,
  `What’s the most ${adj()} way to lose a ${noun()}? Asking for science!`,
  `Would you rather have an extra ${noun()} or an extra sense?`,
  `What's one ${noun()} you’d never want to see again?`,
  `Best hack to make a ${adj()} ${noun()} extra ${exc()}?`,
  `If ${noun()}s could talk, what would their biggest complaint be?`,
  `What emoji best describes a ${adj()} ${noun()}?`,
  `Would you trust a ${exc()} ${noun()} with your secrets?`,
  `What's your go-to place to hide a ${noun()}?`,
];

function adj() {
  let randomAdjsIndex = Math.floor(Math.random() * adjs.length);
  return adjs[randomAdjsIndex];
}
function noun() {
  let randomNounIndex = Math.floor(Math.random() * nouns.length);
  return nouns[randomNounIndex];
}
function exc() {
  let randomExIndex = Math.floor(Math.random() * exclamations.length);
  return exclamations[randomExIndex];
}

module.exports = {
  getQuestion: function () {
    let randomNum = Math.floor(Math.random() * questions.length);
    return questions[randomNum];
  },
  getPersonName: function () {
    let randomFirstIndex = Math.floor(Math.random() * firstNames.length);
    let randomLastIndex = Math.floor(Math.random() * lastNames.length);
    return firstNames[randomFirstIndex] + " " + lastNames[randomLastIndex];
  },
};
